### ISSUE TITLE
Tracker.py and info.py are not working and just throwing errors

### ISSUE THREAD

**Issue by vibharaghu** [JIceberg/grouch#10]
<img width="519" alt="Screen Shot 2022-04-13 at 12 41 42 AM" src="https://user-images.githubusercontent.com/90982699/163103577-9eea1afa-5fcc-4f55-88f5-a0c598be8f45.png">

**Comment by adithya-gv** [comment]
What did you enter as input into the terminal?

**Comment by adithya-gv** [comment]
From what it seems though, just freshly clone the repository, and reinstall the packages using the requirements.txt file. Also make sure you're on Python 3.8 or 3.9 (Python 3.10 is really weird and causes some unwarranted behavior).
